version: "3.7"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # command: ["php", "artisan", "serve", "--host", "0.0.0.0"]
    depends_on:
      - db
    environment:
      LOG_CHANNEL: "errorlog"
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: "base64:0RZzJqqCHu8+tBNz955FHVze/Mx/NpLz/tgTesTOOTE:"
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: m150
      DB_USERNAME: app
      DB_PASSWORD: app

  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
      MYSQL_DATABASE: "m150"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db

    restart: always
    ports:
      - 8080:80

volumes:
  db_data:
